# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-License-Identifier: MIT

[pytest]
addopts = --isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=dcxml --cov-report=term-missing
testpaths = tests dcxml
filterwarnings = ignore::pytest.PytestDeprecationWarning
